# Generated by Django 5.0.2 on 2024-03-04 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Copropriete",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("adresse", models.TextField()),
                (
                    "id_Agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API_keys.agency",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CommonKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="change")),
                ("acces", models.TextField()),
                ("image", models.ImageField(upload_to="key_images/")),
                ("qr_code", models.TextField(blank=True, null=True)),
                (
                    "id_Agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API_keys.agency",
                    ),
                ),
                (
                    "id_Copro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API_keys.copropriete",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrivateKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("acces", models.TextField()),
                ("image", models.ImageField(upload_to="key_images/")),
                ("qr_code", models.TextField(blank=True, null=True)),
                (
                    "id_Agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API_keys.agency",
                    ),
                ),
                (
                    "id_Copro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API_keys.copropriete",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SuperUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField(max_length=30)),
                ("Email", models.EmailField(max_length=50, unique=True)),
                ("Password", models.TextField()),
                (
                    "id_Agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API_keys.agency",
                    ),
                ),
            ],
            options={
                "ordering": ["id_Agency", "Name"],
            },
        ),
        migrations.CreateModel(
            name="TrackCommon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entreprise", models.TextField(max_length=30)),
                ("tel", models.IntegerField()),
                ("depart", models.DateTimeField(auto_now_add=True)),
                ("retour", models.DateTimeField(auto_now=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "id_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API_keys.commonkey",
                    ),
                ),
            ],
            options={
                "ordering": ["depart"],
            },
        ),
        migrations.CreateModel(
            name="TrackPrivate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entreprise", models.TextField(max_length=30)),
                ("tel", models.IntegerField()),
                ("depart", models.DateTimeField(auto_now_add=True)),
                ("retour", models.DateTimeField(auto_now=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "id_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API_keys.privatekey",
                    ),
                ),
            ],
            options={
                "ordering": ["depart"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField(max_length=30)),
                ("Email", models.EmailField(max_length=50, unique=True)),
                ("Password", models.TextField()),
                (
                    "id_Agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API_keys.agency",
                    ),
                ),
                (
                    "id_SuperUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API_keys.superuser",
                    ),
                ),
            ],
            options={
                "ordering": ["id_Agency", "Name"],
            },
        ),
    ]
