# Generated by Django 5.0.2 on 2024-03-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonkey",
            name="name",
            field=models.TextField(),
        ),
    ]
