# Generated by Django 5.0.2 on 2024-03-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0002_alter_commonkey_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="copropriete",
            name="name",
            field=models.TextField(default="default", max_length=20),
            preserve_default=False,
        ),
    ]
