# Generated by Django 5.0.2 on 2024-03-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0003_copropriete_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="copropriete",
            name="Numero",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="copropriete",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
