# Generated by Django 5.0.2 on 2024-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0004_copropriete_numero_alter_copropriete_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonkey",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="privatekey",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
