# Generated by Django 5.0.2 on 2024-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0005_commonkey_available_privatekey_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackcommon",
            name="retour",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trackprivate",
            name="retour",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
