# Generated by Django 5.0.2 on 2024-03-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0006_alter_trackcommon_retour_alter_trackprivate_retour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatekey",
            name="image",
            field=models.ImageField(blank=True, upload_to="key_images/"),
        ),
    ]
