# Generated by Django 5.0.2 on 2024-03-10 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0009_rename_superuser_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id_SuperUser",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["id_Agency", "firstname"]},
        ),
        migrations.RemoveField(
            model_name="user",
            name="Email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="Name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="Password",
        ),
        migrations.AddField(
            model_name="agency",
            name="Adresse",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="firstname",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lastname",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agency",
            name="Name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="agency",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="Manager",
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=1, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
    ]
