# Generated by Django 5.0.2 on 2024-03-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0011_user_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("is_manager", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["firstname"],
            },
        ),
    ]
