# Generated by Django 5.0.2 on 2024-03-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0013_delete_superuser_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agency",
            options={"ordering": ["Name"]},
        ),
        migrations.AddField(
            model_name="agency",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="password",
            field=models.CharField(default=1, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
