# Generated by Django 5.0.2 on 2024-03-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0014_alter_agency_options_agency_last_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="email",
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agency",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
