# Generated by Django 5.0.2 on 2024-04-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0016_trackcommon_id_agency_trackprivate_id_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="otp",
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="otp_create",
            field=models.DateField(blank=True, null=True),
        ),
    ]
