# Generated by Django 5.0.2 on 2024-04-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0017_agency_otp_agency_otp_create"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="otp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
