# Generated by Django 5.0.2 on 2024-04-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0018_alter_agency_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="otp_create",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
