# Generated by Django 5.0.2 on 2024-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0019_alter_agency_otp_create"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="email_verif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agency",
            name="otp_valid",
            field=models.BooleanField(default=False),
        ),
    ]
