# Generated by Django 5.0.2 on 2024-04-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0020_agency_email_verif_agency_otp_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="otp_valid_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
