# Generated by Django 5.0.2 on 2024-04-14 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0021_agency_otp_valid_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="otp_valid",
        ),
    ]
