# Generated by Django 5.0.2 on 2024-04-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0022_remove_agency_otp_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="date_token",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="token",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
