# Generated by Django 5.0.2 on 2024-04-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "API_keys",
            "0025_alter_trackcommon_options_alter_trackprivate_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatekey",
            name="acces",
            field=models.TextField(max_length=50),
        ),
    ]
