# Generated by Django 5.0.2 on 2024-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0026_alter_privatekey_acces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonkey",
            name="acces",
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name="privatekey",
            name="acces",
            field=models.TextField(max_length=30),
        ),
    ]
