# Generated by Django 5.0.2 on 2024-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0027_alter_commonkey_acces_alter_privatekey_acces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonkey",
            name="acces",
            field=models.TextField(max_length=36),
        ),
        migrations.AlterField(
            model_name="privatekey",
            name="acces",
            field=models.TextField(max_length=26),
        ),
    ]
