# Generated by Django 5.0.2 on 2024-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_keys", "0028_alter_commonkey_acces_alter_privatekey_acces"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="copropriete",
            options={"ordering": ["Numero"]},
        ),
        migrations.AlterField(
            model_name="commonkey",
            name="name",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="privatekey",
            name="acces",
            field=models.TextField(max_length=27),
        ),
    ]
